@AKS.Kargo.AnalysisRun.Logs_HostAddress = http://localhost:8080

GET {{AKS.Kargo.AnalysisRun.Logs_HostAddress}}/logs/dev/argo-cd/argo-cd-argocd-application-controller/application-controller
###

# curl http://localhost:8080/logs/dev/argo-cd/argo-cd-argocd-application-controller/application-controller