apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aks-kargo-analysisrun-logs.fullname" . }}
  labels:
    {{- include "aks-kargo-analysisrun-logs.labels" . | nindent 4 }}
data:
  appsettings.Production.json: {{ dict "settings" .Values.settings | toJson | b64enc | quote }}